services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:1.1.8-2
    ports:
      - 21114:21114
      - 21115:21115
      - 21116:21116
      - 21118:21118
    command: hbbs
    volumes:
      - ./data:/root
    network_mode: "host"

    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:1.1.8-2
    ports:
      - 21117:21117
      - 21119:21119
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: "host"
    restart: unless-stopped
